// internal/models/bedrock.go
package models

import "encoding/json"

// TokenUsage captures the Bedrock usage statistics returned by Claude.
type TokenUsage struct {
	InputTokens    int `json:"input"`    // tokens used for the prompt
	OutputTokens   int `json:"output"`   // tokens generated by the model
	ThinkingTokens int `json:"thinking"` // internal “thinking” budget tokens
	TotalTokens    int `json:"total"`    // aggregate total (input + output + thinking)
}

// BedrockResponse is the in-memory representation of a Claude Converse result.
type BedrockResponse struct {
	Raw       json.RawMessage `json:"raw"`       // exact JSON payload from Bedrock
	Processed interface{}     `json:"processed"` // parsed / summarised analysis object
	TokenUsage
	RequestID string `json:"requestId"` // X-Amzn-RequestId header from Bedrock
}
